services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
